### ISSUE TITLE
[BUG]: Unable to build project when sub-package is used

### ISSUE THREAD

**Issue by dhirajhimani** [FlutterGen/flutter_gen#374] opened 2023-03-29 14:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.2.0

### Command type

build_runner (Default)

### What happened?

Create a sub-package in the main project:- flutter create --template=package demo

After adding the entry in the pubspec.yaml, for the local package, the build_runner doesn't work, but if the flutter_gen is removed, it works. 

### Relevant a pubspec.yaml.

```yaml
name: app


dependencies:
   demo:
    path: demo/
  flutter:
    sdk: flutter


dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen: ^5.2.0
  flutter_gen_runner: ^5.2.0

flutter_gen:
  output: lib/app/generated/
  integration:
    flutter_svg: true

import_sorter:
  ignored_files:
    - \/lib\/*.g.dart
    - \/lib\/*.freezed.dart
    - \/lib\/*.config.dart
    - \/lib\/*.chopper.dart
    - \/lib\/*.mocks.dart

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/env/
```

### Relevant log output

```shell
The pubspec.lock file has changed since the .dart_tool/package_config.json file was generated, please run "flutter pub get" again.
pub finished with exit code 65
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Raviteja11122** [comment] 2023-03-31 09:37
Any update on this issue?

**Comment by egyleader** [comment] 2023-04-06 13:53
me too facing this issue on futter 3.7.10

**Comment by wasabeef** [comment] 2023-04-18 06:40
Pleases `flutter_gen: ^5.2.0` remove it!

**Comment by dhirajhimani** [comment] 2023-04-18 07:25
But it gives following error 

`  Bad state: Unable to generate package graph, no  'dart_tool/flutter_gen/pubspec.yaml' found. `

**Comment by egyleader** [comment] 2023-04-20 16:45
## Temp workaround 

this is a temp workaround to continue development with this package until this issue is fixed :

1. comment all the sub-packages in pubspec.yaml
2. add   the required packages & configuration for fluttergen
```yaml
dev_dependencies:
  flutter_gen: ^5.3.0
  flutter_gen_runner: ^5.3.0
   build_runner: ^2.2.0

flutter_gen:
  output: lib/generated/assets
  integrations:
    flutter_svg: true
```
3. run the build command `flutter pub run build_runner build --delete-conflicting-outputs`
this will generate all the assets code .

4.  comment the fluttergen packages & configuration  and uncomment the subpackages 
this is to avoid build conflicts with other code generation & use sub packages.

**Comment by dhirajhimani** [comment] 2023-05-04 18:03
thanks, 
luckily, i needed a small sub module, so i handled it.

**Comment by EArminjon** [comment] 2023-09-14 09:34
I create a reproductible project: https://github.com/EArminjon/flutter-issue

```
flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs
```

```
The pubspec.lock file has changed since the .dart_tool/package_config.json file was generated, please run "flutter pub get" again.
pub finished with exit code 65
```

**Comment by JSBmanD** [comment] 2024-02-13 22:03
Still having the problem on latest flutter. Any news?

**Comment by EArminjon** [comment] 2024-02-13 23:38
> Still having the problem on latest flutter. Any news?

Upgrade flutter to the latest release.

**Comment by JSBmanD** [comment] 2024-02-14 03:05
> > Still having the problem on latest flutter. Any news?
> 
> Upgrade flutter to the latest release. I got this issue With 3.7 and no longer with 3.16

I'm on 3.16.5, still have this issue, need to delete lock file every time issue appears

**Comment by AlexV525** [comment] 2024-03-06 21:45
I cannot reproduce this with the example of the library using Flutter 3.16.

<img width="922" alt="image" src="https://github.com/FlutterGen/flutter_gen/assets/15884415/f4e5c381-6a79-4c30-a1cb-900ed98fb8da">

As @wasabeef suggested above, removing `flutter_gen` as a dependency might help to solve this.

Closing this as cannot reproduce, and please submit a minimal reproducible example (project with sub-package) with a new issue.

**Closed by AlexV525** 2024-03-06 21:45 UTC
Labels: bug
